export const contactUsContent = {
  en: {
    title: "Book A Consultation NOW",
    description:
      "Ready to take the next step?\n Schedule your meeting with us today !",
    secondTitle: "OR Leave Your information",
    secondDescription:
      "Leave us your details, and we'll contact you right away to arrange a convenient time!",
    campusTitle: "1. Which of the following campus can you attend?",
    bookingTitle:
      "2. Booking Information (Please fill in either one of these two fields)",
    parentInfo: "Parent / Guardian Information",
    studentInfo: "Student Information",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    trialDetails: "3. Trial Lesson Details",
    AddTrailText: "Trial Lesson for More than One Child?",
    schoolYear: "Current School Year",
    subject: "Subject",
    addStudent: "+ Add Another Student Information",
    questionsTitle: "4. Any Specific Question or Concerns",
    contactTitle: "5. Preferred Contact Method",
    sendButton: "SEND REQUEST",
    selectGrade: "Current School Year / Grade*",
    selectSubjects: "Subject for the trial lesson*",
    grades: ["Preschool", "Elementary School", "Middle School", "High School"],
    subjects: [
      "Year 9 English",
      "Year 10 Science",
      "Year 11 EAL",
      "Year 12 Maths",
      "Year 9 Japanese",
      "Maths Advanced (Elite Program)",
    ],
    contactMethods: ["Phone call", "Message", "Email"],
    contactUsTitle: "Contact Us",
    contactUs: [
      {
        title: "Box Hill Campus Melbourne",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "email@austin.com.au",
        QRCode: "/contact_us/QRcode-box-hill.png",
        about: [
          {
            title: "Y1-6",
            phone: ["+61 3 9899 8888", "+61 3 9899 8888", "+61 3 9899 8888"],
            we_chat: "Austin_bh",
            whatsapp: "+61 3 9899 8888",
            discord: "ryanyanaustinbh",
          },
          {
            title: "Y7-9",
            phone: ["+61 3 9899 8888"],
            we_chat: "Austin_bh",
            whatsapp: "+61 3 9899 8888",
            discord: "ryanyanaustinbh",
          },
          {
            title: "Y10-12",
            phone: ["+61 3 9899 8888"],
            we_chat: "Austin_bh",
            whatsapp: "+61 3 9899 8888",
            discord: "ryanyanaustinbh",
          },
        ],
      },
      {
        title: "Mount Waverley Campus Melbourne",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "email@austin.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-6",
            phone: ["+61 3 9899 8888", "+61 3 9899 8888", "+61 3 9899 8888"],
            we_chat: "Austin_bh",
            whatsapp: "+61 3 9899 8888",
            discord: "ryanyanaustinbh",
          },
          
        ],
      },
      {
        title: "Mount Waverley Ausyouth Campus - Melbourne",
        location: "Level 1, 304 Stephensons Road, Mount Waverley",
        email: "email@austin.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-6",
            phone: ["0468541027", "0426800815(Chinese)", "0452570815(Chinese)"],
            we_chat: "Austin_bh",
            whatsapp: "+61 3 9899 8888",
            discord: "ryanyanaustinbh",
          },
          
        ],
      },
    ],
    OtherMethods: "You can also find us in",
  },
  zh: {
    title: "填写表格预约试听课",
    description:
      "在正式开课前，我们将根据您提供的信息为您提供免费咨询，帮助您找到最适合的试听课程。",
    campusTitle: "1. 您可以选择以下哪个校区？",
    bookingTitle: "2. 预约信息（请填写以下任意一项）",
    parentInfo: "家长/监护人信息",
    studentInfo: "学生信息",
    fullName: "姓名",
    email: "电子邮箱",
    phone: "联系电话",
    trialDetails: "3. 试听课程详情",
    AddTrailText: "试听课程适用于多个孩子？",
    schoolYear: "当前学年",
    subject: "科目",
    addStudent: "+ 添加其他学生信息",
    questionsTitle: "4. 特别问题或关注事项",
    contactTitle: "5. 首选联系方式",
    sendButton: "发送请求",
    selectGrade: "选择年级",
    selectSubjects: "选择科目",
    grades: ["学前班", "小学", "初中", "高中"],
    subjects: [
      "九年级英语",
      "十年级科学",
      "十一年级EAL",
      "十二年级数学",
      "九年级日语",
      "数学进阶（精英课程）",
    ],
    contactMethods: ["电话", "短信", "电子邮件"],
  },
};
