export const contactUsContent = {
  en: {
    title: "Book A Consultation NOW",
    description:
      "Ready to take the next step?\n Schedule your meeting with us today !",
    secondTitle: "OR Leave Your information",
    secondDescription:
      "Leave us your details, and we'll contact you right away to arrange a convenient time!",
    campusTitle: "1. Which of the following campus can you attend?",
    bookingTitle:
      "2. Booking Information (Please fill in either one of these two fields)",
    parentInfo: "Parent / Guardian Information",
    studentInfo: "Student Information",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    trialDetails: "3. Trial Lesson Details",
    AddTrailText: "Trial Lesson for More than One Child?",
    schoolYear: "Current School Year",
    subject: "Subject",
    addStudent: "+ Add Another Student Information",
    questionsTitle: "4. Any Specific Question or Concerns",
    contactTitle: "5. Preferred Contact Method",
    sendButton: "SEND REQUEST",
    selectGrade: "Current School Year / Grade*",
    selectSubjects: "Subject for the trial lesson*",
    grades: ["Preschool", "Elementary School", "Middle School", "High School"],
    subjects: [
      "Year 9 English",
      "Year 10 Science",
      "Year 11 EAL",
      "Year 12 Maths",
      "Year 9 Japanese",
      "Maths Advanced (Elite Program)",
    ],
    contactMethods: ["Phone call", "Message", "Email"],
    contactUsTitle: "Contact Us",
    contactUs: [
      {
        title: "Box Hill Campus - Melbourne",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "info@autinedu.com.au",
        QRCode: "/contact_us/QRcode-box-hill.png",
        about: [
          {
            title: "Y1-6",
            phone: ["0466 822 995 (English)", "0433 860 815 (Chinese)"],
            we_chat: "Austin-boxhill ",
            whatsapp: "0466 822 995",
            discord: "austincelia",
          },
          {
            title: "Y7-9",
            phone: ["0466 822 995 (English)", "0452 570 815 (Chinese)"],
            we_chat: "Austin_bh2",
            whatsapp: "0466 822 995",
            discord: "austincelia",
          },
          {
            title: "Y10-12",
            phone: ["0466 822 995 (English)", "0452 570 815 (Chinese)"],
            we_chat: "Austin_bh",
            whatsapp: "0466 822 995",
            discord: "ryanyanaustinbh",
          },
        ],
      },
      {
        title: "Mount Waverley VCE Campus - Melbourne",
        location: "8 The Highway,Mount Waverley,VIC 3149",
        email: "mt.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y10-12",
            phone: ["0432 546 815 (English)", "0406 508 127 (Chinese)"],
            we_chat: "Austin_bh",
            whatsapp: "austinedusyndal",
            discord: "austinmwkathy",
          },
        ],
      },
      {
        title: "Mount Waverley Ausyouth Campus - Melbourne",
        location: "Level 1, 304 Stephensons Road, Mount Waverley",
        email: "mt.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-9",
            phone: ["0422 099 665"],
            we_chat: "austinJunior",
            whatsapp: "0422 099 665",
            discord: "mtausyouth",
          },
        ],
      },
      {
        title: "CBD Campus - Melbourne",
        location: "Level 6, 51 Queens Street, Melbourne, VIC 3000",
        email: "city.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-12",
            phone: ["0450 206 886"],
            we_chat: "Austinedu_city",
            whatsapp: "0450 206 886",
            discord: "kat06513000",
          },
        ],
      },
      {
        title: "Point Cook Campus - Melbourne",
        location: "29C/428 Old Geelong Road, Hoppers Crossing, VIC 3029",
        email: "pointcook@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-12",
            phone: ["0405 329 666"],
            we_chat: "Austinpc",
          },
        ],
      },
      {
        title: "South Australia Campus - Adelaide",
        location: "17 O'Brien st, Adelaide 5000, SA",
        email: "saadmin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "Y1-12",
            phone: ["0431 178 409"],
            we_chat: "AustinADL1",
            whatsapp: "0431 178 409",
            discord: "austineducation",
          },
        ],
      },
      {
        title: "Ausyouth Music - Melbourne",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "ninadu@ausyouthmusic.com",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            phone: ["0438 799 516"],
            we_chat: "AusYouthMusic",
            whatsapp: "0438 799 516",
          },
        ],
      },
    ],
    OtherMethods: "You can also find us in",
  },
  zh: {
    title: "填写表格立即预约咨询",
    description: "准备好迈出下一步了吗？\n立即与我们安排会面！",
    secondTitle: "或者留下您的信息",
    secondDescription: "留下您的联系方式，我们会尽快与您联系，安排合适的时间！",
    campusTitle: "1. 以下哪个校区您方便到访？",
    bookingTitle: "2. 预约信息（请填写以下两项中的一项）",
    parentInfo: "家长／监护人信息",
    studentInfo: "学生信息",
    fullName: "姓名",
    email: "电子邮箱",
    phone: "联系电话",
    trialDetails: "3. 试听课程详情",
    AddTrailText: "多个孩子需要试听吗？",
    schoolYear: "当前学年",
    subject: "试听科目",
    addStudent: "+ 添加更多学生信息",
    questionsTitle: "4. 是否有任何特别问题或疑虑",
    contactTitle: "5. 首选联系方式",
    sendButton: "提交申请",
    selectGrade: "选择年级*",
    selectSubjects: "选择试听科目*",
    grades: ["学前班", "小学", "初中", "高中"],
    subjects: [
      "九年级英语",
      "十年级科学",
      "十一年级EAL",
      "十二年级数学",
      "九年级日语",
      "数学进阶（精英课程）",
    ],
    contactMethods: ["电话", "短信", "电子邮件"],
    contactUsTitle: "联系我们",
    contactUs: [
      {
        title: "墨尔本 Box Hill 校区",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "info@autinedu.com.au",
        QRCode: "/contact_us/QRcode-box-hill.png",
        about: [
          {
            title: "1-6年级",
            phone: ["0466 822 995 (English)  ", "0433 860 815 (Chinese) "],
            we_chat: "Austin-boxhill ",
            whatsapp: "0466 822 995 ",
            discord: "austincelia",
          },
          {
            title: "7-9年级",
            phone: ["0466 822 995 (English)", "0452 570 815 (Chinese)"],
            we_chat: "Austin_bh2",
            whatsapp: "0466 822 995",
            discord: "austincelia",
          },
          {
            title: "10-12年级",
            phone: ["0466 822 995 (English)", "0452 570 815 (Chinese)"],
            we_chat: "Austin_bh",
            whatsapp: "0466 822 995",
            discord: "ryanyanaustinbh",
          },
        ],
      },
      {
        title: "墨尔本 Mount Waverley VCE 校区",
        location: "8 The Highway,Mount Waverley,VIC 3149",
        email: "mt.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "10-12年级",
            phone: ["0432 546 815 (English) ", "0406 508 127 (Chinese)"],
            we_chat: "austinedusyndal ",
            whatsapp: "0406 508 127",
            discord: "austinmwkathy",
          },
        ],
      },
      {
        title: "墨尔本 AusYouth 青少部校区",
        location: "Level 1, 304 Stephensons Road, Mount Waverley",
        email: "mt.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "1-9年级",
            phone: ["0422 099 665"],
            we_chat: "austinJunior",
            whatsapp: "0422 099 665",
            discord: "mtausyouth",
          },
        ],
      },
      {
        title: "墨尔本 CBD 校区",
        location: "Level 6, 51 Queens Street, Melbourne, VIC 3000",
        email: "city.admin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "1-12年级",
            phone: ["0450 206 886"],
            we_chat: "Austinedu_city",
            whatsapp: "0450 206 886",
            discord: "kat06513000",
          },
        ],
      },
      {
        title: "墨尔本 Point Cook 校区",
        location: "29C/428 Old Geelong Road, Hoppers Crossing, VIC 3029",
        email: "pointcook@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "1-12年级",
            phone: ["0405 329 666"],
            we_chat: "Austinpc",
          },
        ],
      },
      {
        title: "南澳 阿德莱德 校区",
        location: "17 O'Brien st, Adelaide 5000, SA",
        email: "saadmin@austinedu.com.au",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            title: "1-12年级",
            phone: ["0431 178 409"],
            we_chat: "AustinADL1",
            whatsapp: "0431 178 409",
            discord: "austineducation",
          },
        ],
      },
      {
        title: "澳升音乐 - Melbourne",
        location: "899 Whitehorse Road, Box Hill, VIC 3128",
        email: "ninadu@ausyouthmusic.com",
        QRCode: "https://placehold.co/400x400",
        about: [
          {
            phone: ["0438 799 516"],
            we_chat: "AusYouthMusic",
            whatsapp: "0438 799 516",
          },
        ],
      },
    ],
    OtherMethods: "您也可以通过以下方式找到我们",
  },
};
